rewrite_articles_task:
  description: >
    Here are some news articles:

    {articles}

    Some of them can have useless info, and some of them can share the same news.
    I want you to write articles about them, each with relevant news, using the originals as resources.
    If two or more articles are talking about the same thing, combine them into one.
    Ignore the useless and irrelevant information and articles.
    Try to write at least {n_news} articles.

    Write them in a magazine style. Maintain the essence and facts,
    but give it a more engaging tone. The text should be
    clear, objective, and captivating, similar to modern editorial styles.
    Remove any kind of publicity. Remove any mention of the source's name/site.
    Remove any kind of markdown. Your output should be in plain text.
    Each article should have at least 4 paragraphs.
    The new articles should be in {language}.
    
    For each generated article, include:

    1. A title (keep it concise and engaging)
    2. The written article
    3. A credit line with the original sources and titles, separated by ";". Example: tech.com - Tech's Title!;ai.com - AI's Title!
    4. The article divider: ---ARTICLE DIVIDER---
    
    The new articles should be in {language}.

    Format your output exactly as follows:
    NEW_TITLE: Your new title here
    NEW_CONTENT: Your rewritten content here
    ORIGINAL_SOURCE: The credit line with the original sources and titles, separated by ";". Example: tech.com - Tech's Title!;ai.com - AI's Title!
    ---ARTICLE DIVIDER---

  expected_output: >
    News articles in magazine style, each with a title, engaging content, 
    a credit line for the original sources and the article divider.
    
  agent: content_rewriter

create_cover_content_task:
  description: >
    Create cover content for a magazine about {topic}. You have access to {n_news} news articles.
    
    First, identify the most relevant and impactful article from the list. For this article:
    1. Create a single impactful word as the main headline. Avoid the words "Revolution" and "Revolução"
    2. Create a catchy subheading based on the article (one short phrase)
    
    Then, select two other random articles and create a brief summary related to each, 
    consisting of exactly ONE short sentence per article.

    It all should be in {language}.

    Format your output exactly as follows:
    MAIN_HEADLINE: Your single word here
    SUBHEADING: Your catchy phrase here
    MAIN_ARTICLE_INDEX: Index of the main article (0-based) NUMBER ONLY
    SUMMARY1_INDEX: Index of first summary article (0-based) NUMBER ONLY
    SUMMARY1: Your one-sentence summary here
    SUMMARY2_INDEX: Index of second summary article (0-based) NUMBER ONLY
    SUMMARY2: Your one-sentence summary here

  expected_output: >
    Cover content including main headline, subheading, and brief summaries for two additional articles.
    
  agent: cover_designer


